name: First Workflow
on: workflow_dispatch
jobs:
 first-job:
   runs-on: ubuntu-latest
   steps:
    - name: Print greeting
      run: echo "Hello World"
      run: echo "Hello Universe"
      run: echo "Hello Galaxy"
    - name: Print goodbye
      run: echo "Done- bye!"
